*** Variables ***
${GLOBAL_SCHEMA_LOGIN}  ${CURDIR}\\..\\schemas\\login.json
${GLOBAL_SCHEMA_ERROR}  ${CURDIR}\\..\\schemas\\error.json
${GLOBAL_SCHEMA_USERS_ID}  ${CURDIR}\\..\\schemas\\users_id.json
${GLOBAL_SCHEMA_USERS}  ${CURDIR}\\..\\schemas\\users.json
${GLOBAL_SCHEMA_USER_POST}  ${CURDIR}\\..\\schemas\\users_post.json
${GLOBAL_SCHEMA_ERROR_CONTRACTS}  ${CURDIR}\\..\\schemas\\error_contracts.json
${GLOBAL_SCHEMA_USER_DELETE}  ${CURDIR}\\..\\schemas\\users_delete.json